project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null

compiler:
    evm_version: null
    solc:
        version: 0.8.0
        #version: 0.5.12 # needed for StandardBounties
        optimizer:
            enabled: true
            runs: 200
        remappings: 
          "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"


dotenv: .env